"""
AQILA — ChromaDB Indexing + Retrieval
Owner: M1 — AI / ML + RAG Core

P0:
    - Index parsed chunks into documents_col
    - Embed query with MiniLM
    - Retrieve top-8 document chunks
    - Return RetrievalResult-compatible dictionaries
"""

from typing import Any

from backend.app.db.chroma import documents_col
from backend.app.schemas.models import RetrievalResult

from .embedder import embed_texts


# ---------------------------------------------------------------------------
# CHROMADB INDEXING
# ---------------------------------------------------------------------------

def index_chunks(
    chunks: list[dict[str, Any]],
    source_type: str = "pdf",
    file_created_at: str | None = None,
) -> int:
    """
    Embed and index parsed chunks into ChromaDB.

    Args:
        chunks:
            Output from rag.parsers.parse_and_chunk()

        source_type:
            pdf / docx

        file_created_at:
            Optional source file creation timestamp.

    Returns:
        Number of chunks indexed.
    """

    if not chunks:
        return 0

    texts = [
        chunk["text"]
        for chunk in chunks
        if chunk.get("text")
    ]

    if not texts:
        return 0

    embeddings = embed_texts(texts)

    ids: list[str] = []
    documents: list[str] = []
    metadatas: list[dict[str, Any]] = []

    embedding_index = 0

    for chunk in chunks:
        text = chunk.get("text")

        if not text:
            continue

        source_id = chunk["source_id"]
        chunk_index = chunk["chunk_index"]

        # Stable unique ID for ChromaDB.
        chunk_id = f"{source_id}:{chunk_index}"

        ids.append(chunk_id)
        documents.append(text)

        metadata: dict[str, Any] = {
            "source_id": source_id,
            "file_name": chunk["file_name"],
            "modality": chunk.get("modality", "text"),
            "chunk_index": chunk_index,
            "source_type": source_type,
        }

        page_number = chunk.get("page_number")

        if page_number is not None:
            metadata["page_number"] = page_number

        if file_created_at is not None:
            metadata["file_created_at"] = file_created_at

        metadatas.append(metadata)

        embedding_index += 1

    if not ids:
        return 0

    # ChromaDB accepts explicit embeddings generated by MiniLM.
    documents_col.upsert(
        ids=ids,
        documents=documents,
        embeddings=embeddings,
        metadatas=metadatas,
    )

    return len(ids)


# ---------------------------------------------------------------------------
# P0 TEXT RETRIEVAL
# ---------------------------------------------------------------------------

def retrieve_text_p0(
    query: str,
    top_k: int = 8,
) -> list[RetrievalResult]:
    """
    Retrieve the top-k text chunks from documents_col.

    Query:
        User's natural-language question.

    Returns:
        list[RetrievalResult]
    """

    if not query or not query.strip():
        return []

    query_embedding = embed_texts([query])[0]

    result = documents_col.query(
        query_embeddings=[query_embedding],
        n_results=top_k,
        include=[
            "documents",
            "metadatas",
            "distances",
            "embeddings",
        ],
    )

    documents = result.get("documents", [[]])[0]
    metadatas = result.get("metadatas", [[]])[0]
    distances = result.get("distances", [[]])[0]
    embeddings = result.get("embeddings", [[]])[0]

    retrieval_results: list[RetrievalResult] = []

    for index, text in enumerate(documents):
        metadata = metadatas[index] or {}

        distance = distances[index]

        # Chroma's cosine distance is:
        #     1 - cosine_similarity
        #
        # Convert to similarity score in [0, 1].
        score = max(
            0.0,
            min(
                1.0,
                1.0 - float(distance),
            ),
        )

        embedding = None

        if embeddings is not None and index < len(embeddings):
    	    embedding = list(embeddings[index])

        source_type = metadata.get(
            "source_type",
            "pdf",
        )

        modality = metadata.get(
            "modality",
            "text",
        )

        page_number = metadata.get(
            "page_number"
        )

        file_created_at = metadata.get(
            "file_created_at"
        )

        chunk_id = f"{metadata['source_id']}:{metadata['chunk_index']}"

        retrieval_results.append(
            RetrievalResult(
                query=query,
                source_id=metadata["source_id"],
                source_type=source_type,
                chunk_id=chunk_id,
                text=text,
                score=score,
                modality=modality,
                page_number=page_number,
                timestamp_start=None,
                timestamp_end=None,
                file_name=metadata["file_name"],
                file_created_at=file_created_at,
                metadata=metadata,
                embedding=embedding,
                embedding_space="minilm",
            )
        )

    return retrieval_results

# ---------------------------------------------------------------------------
# P1 AUDIO INDEXING
# ---------------------------------------------------------------------------

def index_audio_chunks(
    segments: list[dict[str, Any]],
    source_id: str,
    file_name: str,
) -> int:
    """
    Embed Whisper transcript segments and index them into audio_col.
    """

    from backend.app.db.chroma import audio_col

    if not segments:
        return 0

    valid_segments = [
        segment
        for segment in segments
        if segment.get("text", "").strip()
    ]

    if not valid_segments:
        return 0

    texts = [
        segment["text"].strip()
        for segment in valid_segments
    ]

    embeddings = embed_texts(texts)

    ids: list[str] = []
    documents: list[str] = []
    metadatas: list[dict[str, Any]] = []

    for index, (segment, embedding) in enumerate(
        zip(valid_segments, embeddings)
    ):
        chunk_id = f"{source_id}:{index}"

        ids.append(chunk_id)
        documents.append(segment["text"].strip())

        metadatas.append(
            {
                "source_id": source_id,
                "file_name": file_name,
                "modality": "audio",
                "chunk_index": index,
                "source_type": "audio",
                "timestamp_start": segment.get("timestamp_start"),
                "timestamp_end": segment.get("timestamp_end"),
            }
        )

    audio_col.upsert(
        ids=ids,
        documents=documents,
        embeddings=embeddings,
        metadatas=metadatas,
    )

    return len(ids)

# ---------------------------------------------------------------------------
# P1 AUDIO RETRIEVAL
# ---------------------------------------------------------------------------

def retrieve_audio_p1(
    query: str,
    top_k: int = 4,
) -> list[RetrievalResult]:
    """
    Retrieve timestamped audio transcript chunks from audio_col.
    """

    from backend.app.db.chroma import audio_col

    if not query or not query.strip():
        return []

    if audio_col.count() == 0:
        return []

    query_embedding = embed_texts([query])[0]

    result = audio_col.query(
        query_embeddings=[query_embedding],
        n_results=min(top_k, audio_col.count()),
        include=[
            "documents",
            "metadatas",
            "distances",
            "embeddings",
        ],
    )

    documents = result.get("documents", [[]])[0]
    metadatas = result.get("metadatas", [[]])[0]
    distances = result.get("distances", [[]])[0]
    embeddings = result.get("embeddings", [[]])[0]

    retrieval_results: list[RetrievalResult] = []

    for index, text in enumerate(documents):
        metadata = metadatas[index] or {}

        distance = distances[index]

        score = max(
            0.0,
            min(
                1.0,
                1.0 - float(distance),
            ),
        )

        embedding = None

        if embeddings is not None and index < len(embeddings):
            embedding = list(embeddings[index])

        source_id = metadata["source_id"]
        chunk_index = metadata["chunk_index"]

        retrieval_results.append(
            RetrievalResult(
                query=query,
                source_id=source_id,
                source_type="audio",
                chunk_id=f"{source_id}:{chunk_index}",
                text=text,
                score=score,
                modality="audio",
                page_number=None,
                timestamp_start=metadata.get("timestamp_start"),
                timestamp_end=metadata.get("timestamp_end"),
                file_name=metadata["file_name"],
                file_created_at=None,
                metadata=metadata,
                embedding=embedding,
                embedding_space="minilm",
            )
        )

    return retrieval_results